# Generated by Django 4.2 on 2025-08-25 00:30

import agents.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('desc', models.CharField(max_length=700)),
                ('phone', models.CharField(max_length=11)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('whatsapp', models.URLField(blank=True, null=True)),
                ('identity_type', models.FileField(choices=[('National Identification number', 'National Identification Number'), ("Driver's License", "Driver's License"), ('International Passport', 'International Passport')], upload_to='')),
                ('identity_image', models.FileField(default='id.jpg', upload_to=agents.models.user_directory_path)),
                ('verified', models.BooleanField(default=False)),
                ('min_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('max_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('agent_id', models.CharField(default=agents.models.generate_aid, max_length=20, unique=True)),
                ('agent_type', models.CharField(choices=[('Realtor', 'Realtor'), ('Property Manager', 'Property Manager'), ('Property Owner', 'Property Owner'), ('Leasing Agent', 'Leasing Agent')], max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('years_of_exp', models.IntegerField(help_text='How many years')),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Agents',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Tour Booked', 'Tour Booked'), ('Inquiry Message', 'Inquiry Message'), ('Apartment Booked', 'Apartment Booked'), ('Property Approved', 'Property Approved'), ('Property Rejected', 'Property Rejected'), ('Verification Updated', 'Verification Updated')], default=None, max_length=100)),
                ('seen', models.BooleanField(default=False)),
                ('nid', models.CharField(default=agents.models.generate_nid, max_length=20, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_notifications', to='agents.agent')),
            ],
            options={
                'verbose_name_plural': 'Notifications',
            },
        ),
        migrations.CreateModel(
            name='BrokerAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=11)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('whatsapp', models.URLField(blank=True, null=True)),
                ('identity_type', models.FileField(choices=[('National Identification number', 'National Identification Number'), ("Driver's License", "Driver's License"), ('International Passport', 'International Passport')], upload_to='')),
                ('identity_image', models.FileField(default='id.jpg', upload_to=agents.models.broker_directory_path)),
                ('verified', models.BooleanField(default=False)),
                ('broker_id', models.CharField(default=agents.models.generate_bid, max_length=20, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('years_of_exp', models.IntegerField(help_text='How many years')),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='brokers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Agents',
            },
        ),
    ]
