# Generated by Django 4.2 on 2025-08-25 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brokeragent',
            options={'verbose_name_plural': 'Brokers'},
        ),
    ]
