# Generated by Django 4.2 on 2025-08-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_alter_brokeragent_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='image',
            field=models.ImageField(default='agent.jpg', upload_to='agent_images'),
        ),
        migrations.AddField(
            model_name='brokeragent',
            name='image',
            field=models.ImageField(default='agent.jpg', upload_to='agent_images'),
        ),
    ]
