# Generated by Django 4.2 on 2025-08-28 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_categories_options'),
        ('agents', '0004_alter_agent_identity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.apartment'),
        ),
        migrations.AddField(
            model_name='notification',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.house'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('House Tour', 'House Tour'), ('Inquiry Message', 'Inquiry Message'), ('Apartment Booked', 'Apartment Booked'), ('Property Approved', 'Property Approved'), ('Property Rejected', 'Property Rejected'), ('Verification Updated', 'Verification Updated')], default=None, max_length=100),
        ),
    ]
