# Generated by Django 4.2 on 2025-09-03 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_notification_apartment_notification_house_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='cover_img',
            field=models.ImageField(default='agent_cover.jpg', upload_to='agent_cover_images'),
        ),
        migrations.AddField(
            model_name='agent',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agent',
            name='office_address',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='office_name',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brokeragent',
            name='office_address',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brokeragent',
            name='office_name',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AgentSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('about', models.TextField(blank=True, max_length=100, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='agents.agent')),
            ],
            options={
                'verbose_name_plural': 'Agent Specialties',
            },
        ),
    ]
