# Generated by Django 4.2 on 2025-09-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_agent_cover_img_agent_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='office_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='office_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
