# Generated by Django 4.2 on 2025-09-28 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_agentreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentspecialization',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent', to='agents.agent'),
        ),
    ]
