# Generated by Django 4.2 on 2025-08-25 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_categories_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='city',
            field=models.CharField(blank=True, choices=[('Umuahia', 'Umuahia'), ('Ibadan', 'Ibadan'), ('Jos', 'Jos'), ('Ilorin', 'Ilorin'), ('Ikeja', 'Ikeja')], default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='state',
            field=models.CharField(choices=[('Abia', 'Abia'), ('Oyo', 'Oyo'), ('Plateau', 'Plateau'), ('Kwara', 'Kwara'), ('Lagos', 'Lagos')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('PayPal', 'PayPal'), ('Stripe', 'Stripe'), ('Flutterwave', 'Flutterwave'), ('Paystack', 'Paystack'), ('RazorPay', 'RazorPay')], default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='city',
            field=models.CharField(blank=True, choices=[('Umuahia', 'Umuahia'), ('Ibadan', 'Ibadan'), ('Jos', 'Jos'), ('Ilorin', 'Ilorin'), ('Ikeja', 'Ikeja')], default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='state',
            field=models.CharField(choices=[('Abia', 'Abia'), ('Oyo', 'Oyo'), ('Plateau', 'Plateau'), ('Kwara', 'Kwara'), ('Lagos', 'Lagos')], default=None, max_length=20),
        ),
        migrations.CreateModel(
            name='ApartmentSafety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safety', models.CharField(blank=True, max_length=100, null=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.apartment')),
            ],
            options={
                'verbose_name_plural': 'Apartment Safety',
            },
        ),
        migrations.CreateModel(
            name='ApartmentRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules', models.CharField(blank=True, max_length=100, null=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.apartment')),
            ],
            options={
                'verbose_name_plural': 'Apartment Rules',
            },
        ),
    ]
