# Generated by Django 4.2 on 2025-08-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_apartment_neigbourhood_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housegallery',
            name='image',
            field=models.ImageField(upload_to='house_gallery'),
        ),
    ]
