# Generated by Django 4.2 on 2025-08-26 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_scheduletour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduletour',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
