# Generated by Django 4.2 on 2025-08-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_scheduletour_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduletour',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
