# Generated by Django 4.2 on 2025-08-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_check_in_booking_checked_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='success_id',
            field=models.CharField(default='1234567890', max_length=20, unique=True),
        ),
    ]
