# Generated by Django 4.2 on 2025-08-28 15:44

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_booking_success_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='success_id',
            field=models.CharField(blank=True, default=core.models.generate_success_id, max_length=20, null=True, unique=True),
        ),
    ]
