# Generated by Django 4.2 on 2025-08-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_categories_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='apartment',
        ),
        migrations.AddField(
            model_name='booking',
            name='apartment',
            field=models.ManyToManyField(to='core.apartment'),
        ),
    ]
