# Generated by Django 4.2 on 2025-08-30 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_booking_apartment_booking_apartment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='apartment',
        ),
        migrations.AddField(
            model_name='booking',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.apartment'),
        ),
    ]
