# Generated by Django 4.2 on 2025-10-05 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_alter_agentspecialization_agent'),
        ('core', '0023_alter_apartmentexteriorfeatures_apartment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduletour',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agent'),
        ),
        migrations.AddField(
            model_name='scheduletour',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.house'),
        ),
    ]
