# Generated by Django 4.2 on 2025-10-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_scheduletour_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduletour',
            name='type',
            field=models.CharField(blank=True, choices=[('Request a Tour', 'Request a Tour'), ('Make an Inquiry', 'Make an Inquiry')], default=None, max_length=100, null=True),
        ),
    ]
