# Generated by Django 4.2 on 2025-10-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_scheduletour_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduletour',
            name='message',
            field=models.TextField(max_length=100),
        ),
    ]
