# Generated by Django 4.2 on 2025-08-25 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_apartment_city_apartment_state_and_more'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartmentbookmark',
            options={'verbose_name_plural': 'Apartment Bookmark'},
        ),
        migrations.AlterModelOptions(
            name='housebookmark',
            options={'verbose_name_plural': 'House Bookmark'},
        ),
        migrations.RemoveField(
            model_name='housebookmark',
            name='House',
        ),
        migrations.AlterField(
            model_name='apartmentbookmark',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apartmentbookmark', to='core.apartment'),
        ),
        migrations.AddField(
            model_name='housebookmark',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='housebookmark', to='core.house'),
        ),
    ]
