# Generated by Django 4.2 on 2025-08-25 00:30

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=700)),
                ('address', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='apartment_gallery')),
                ('bedrooms', models.PositiveIntegerField(default=0)),
                ('bathrooms', models.PositiveIntegerField(default=0)),
                ('garage', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('sq_ft', models.DecimalField(decimal_places=2, help_text='Enter the size in square feet', max_digits=10)),
                ('acres', models.DecimalField(decimal_places=2, help_text='Enter the size in acres', max_digits=10)),
                ('featured', models.BooleanField(default=False)),
                ('year_build', models.IntegerField(help_text='Enter the year')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('rejected', 'Rejected'), ('in review', 'In Review'), ('live', 'Live')], default='draft', max_length=20)),
                ('apt_id', models.CharField(default=core.models.generate_apt_id, max_length=20, unique=True)),
                ('is_available', models.BooleanField(default=False)),
                ('neigbourhood_info', models.CharField(blank=True, max_length=255, null=True)),
                ('a_type', models.CharField(blank=True, max_length=255, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment', to='agents.agent')),
            ],
            options={
                'verbose_name_plural': 'Apartments',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, default='category.jpg', null=True, upload_to='images')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=700)),
                ('address', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='house_gallery')),
                ('bedrooms', models.PositiveIntegerField(default=0)),
                ('bathrooms', models.PositiveIntegerField(default=0)),
                ('garage', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('sq_ft', models.DecimalField(decimal_places=2, help_text='Enter the size in square feet', max_digits=10)),
                ('acres', models.DecimalField(decimal_places=2, help_text='Enter the size in acres', max_digits=10)),
                ('featured', models.BooleanField(default=False)),
                ('year_build', models.IntegerField(help_text='Enter the year')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('rejected', 'Rejected'), ('in review', 'In Review'), ('live', 'Live')], default='draft', max_length=20)),
                ('hid', models.CharField(default=core.models.generate_house_id, max_length=20, unique=True)),
                ('is_sold', models.BooleanField(default=False)),
                ('neigbourhood_info', models.CharField(blank=True, max_length=255, null=True)),
                ('h_type', models.CharField(blank=True, max_length=255, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house', to='agents.agent')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categories')),
            ],
            options={
                'verbose_name_plural': 'Houses',
            },
        ),
        migrations.CreateModel(
            name='InteriorFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.house')),
            ],
            options={
                'verbose_name_plural': 'Interior Features',
            },
        ),
        migrations.CreateModel(
            name='HouseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(blank=True, null=True)),
                ('reply', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], default=None)),
                ('active', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='core.house')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'House Reviews',
            },
        ),
        migrations.CreateModel(
            name='HouseGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hoouse_gallery')),
                ('hgid', models.CharField(default=core.models.generate_house_gallery_id, max_length=20, unique=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.house')),
            ],
            options={
                'verbose_name_plural': 'House Gallery',
            },
        ),
        migrations.CreateModel(
            name='ExteriorFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.house')),
            ],
            options={
                'verbose_name_plural': 'Exterior Features',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Processing', 'Processing'), ('Failed', 'Failed')], max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('total_days', models.PositiveIntegerField(default=0)),
                ('check_in', models.BooleanField(default=False)),
                ('check_out', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('checked_in_tracker', models.BooleanField(default=False)),
                ('checked_out_tracker', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('booking_id', models.CharField(default=core.models.generate_booking_id, max_length=20, unique=True)),
                ('apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.apartment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(blank=True, null=True)),
                ('reply', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], default=None)),
                ('active', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='core.apartment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Apartment Reviews',
            },
        ),
        migrations.CreateModel(
            name='ApartmentInteriorFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.apartment')),
            ],
            options={
                'verbose_name_plural': 'Apartment Interior Features',
            },
        ),
        migrations.CreateModel(
            name='ApartmentGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='apartment_gallery')),
                ('agid', models.CharField(default=core.models.generate_apartment_gallery_id, max_length=20, unique=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.apartment')),
            ],
            options={
                'verbose_name_plural': 'Apartment Gallery',
            },
        ),
        migrations.CreateModel(
            name='ApartmentExteriorFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.apartment')),
            ],
            options={
                'verbose_name_plural': 'Apartment Exterior Features',
            },
        ),
        migrations.AddField(
            model_name='apartment',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categories'),
        ),
    ]
