# Generated by Django 4.2 on 2025-08-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_apartmentexteriorfeatures_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='desc',
            field=models.TextField(max_length=700),
        ),
        migrations.AlterField(
            model_name='house',
            name='desc',
            field=models.TextField(max_length=700),
        ),
    ]
