# Generated by Django 4.2 on 2025-08-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_apartment_desc_alter_house_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
