# Generated by Django 4.2 on 2025-08-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_apartment_city_apartment_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='neigbourhood_info',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='neigbourhood_info',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
