# Generated by Django 4.2 on 2025-08-26 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_alter_scheduletour_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduletour',
            name='user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scheduletour',
            name='email',
            field=models.EmailField(default='example@email.com', max_length=254),
        ),
    ]
