# Generated by Django 4.2 on 2025-08-26 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_scheduletour_user_alter_scheduletour_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduletour',
            name='email',
            field=models.EmailField(default='example@email.com', max_length=100),
        ),
    ]
