# Generated by Django 4.2 on 2025-08-27 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_scheduletour_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='check_in',
            new_name='checked_in',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='check_out',
            new_name='checked_out',
        ),
    ]
