# Generated by Django 4.2 on 2025-08-28 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_booking_stripe_payment_intent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
