# Generated by Django 4.2 on 2025-09-04 23:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0020_remove_booking_apartment_booking_apartment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApartmentReview',
            new_name='Review',
        ),
        migrations.DeleteModel(
            name='HouseReview',
        ),
    ]
