# Generated by Django 4.2 on 2025-09-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rename_apartmentreview_review_delete_housereview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='acres',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the size in acres', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='sq_ft',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the size in square feet', max_digits=10, null=True),
        ),
    ]
