# Generated by Django 4.2 on 2025-09-28 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_apartment_acres_alter_apartment_sq_ft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentexteriorfeatures',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.apartment'),
        ),
        migrations.AlterField(
            model_name='apartmentgallery',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.apartment'),
        ),
        migrations.AlterField(
            model_name='apartmentinteriorfeatures',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.apartment'),
        ),
        migrations.AlterField(
            model_name='apartmentrules',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.apartment'),
        ),
        migrations.AlterField(
            model_name='apartmentsafety',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.apartment'),
        ),
        migrations.AlterField(
            model_name='exteriorfeatures',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.house'),
        ),
        migrations.AlterField(
            model_name='housegallery',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.house'),
        ),
        migrations.AlterField(
            model_name='interiorfeatures',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.house'),
        ),
    ]
