# Generated by Django 4.2 on 2025-10-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_scheduletour_agent_scheduletour_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduletour',
            name='type',
            field=models.CharField(choices=[('Request a Tour', 'Request a Tour'), ('Make an Inquiry', 'Make an Inquiry')], default=None, max_length=100),
        ),
    ]
