# Generated by Django 4.2 on 2025-10-05 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_scheduletour_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduletour',
            name='type',
        ),
    ]
