# Generated by Django 4.2 on 2025-08-28 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_categories_options'),
        ('customer', '0003_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='apartment',
        ),
        migrations.AddField(
            model_name='notification',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.booking'),
        ),
    ]
