# Generated by Django 4.2 on 2025-08-26 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agent_image_brokeragent_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='identity_type',
            field=models.CharField(choices=[('National Identification number', 'National Identification Number'), ("Driver's License", "Driver's License"), ('International Passport', 'International Passport')], max_length=100),
        ),
    ]
