# Generated by Django 4.2 on 2025-09-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_alter_agent_office_address_alter_agent_office_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='mission',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
